---
title: "Biol4315_Lab2_RM"
author: "Oceanne.W"
date: "`r format(Sys.time(), '%Y %B, %d')`"
output: 
  html_document:
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Lab2** # {-}

# **Package Installation** ##
  Installation of the relevant packages
    ex. *vegan* and *ggplot2* are installed
```{r, results=FALSE, message=FALSE, warning=FALSE}
if(!require("vegan")){
  install.packages("vegan")
  library("vegan")
  
}
if(!require("ggplot2")){
  install.packages("ggplot2")
  library("ggplot2")
}
```

## **Dune Transformation** ##
Log transformation on the dune dataset
```{r, results=FALSE}
#Load dune data from vegan package
data(dune)
#Reassign to a new variable
dune2 <- dune

#log1p transformation
log1p(dune2)
```

## **NMDS** ##
Perform metaMDS function on dune dataset with default parameters.
```{r, results = FALSE}
#For reproducibility
set.seed(55)
#Default setting used
mdsDune2 <- metaMDS(dune2)
dpoints <- as.data.frame(mdsDune2$points) 
```

## **Plot NMDS** ##
Plot dune dataset MDS points with ggplot
```{r}
pNMDS <- ggplot(dpoints, aes(x=MDS1, y = MDS2))+
  geom_point(size=2)+
  theme_bw(base_size = 16)+
  ggtitle("NMDS Dune dataset Bray")
#Display on canvas 
pNMDS
```
